import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    // Relative base so CSS-embedded asset URLs (background-image, @font-face)
    // resolve correctly wherever the app is deployed — including under a
    // subfolder (e.g. /journal) — without needing an environment-specific
    // rebuild. The @vite() Blade directive's own <link>/<script> tags are
    // unaffected; those are generated by Laravel at runtime via ASSET_URL.
    base: './',
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
                'resources/css/admin.css',
                'resources/js/admin.js',
            ],
            refresh: true,
        }),
    ],
});
